use ethereum_types::U256;

/// Enumerates the errors that can be generated by the program.
#[allow(dead_code)]
#[derive(Debug)]
pub enum ProgramError {
    OutOfGas,
    InvalidOpcode,
    StackUnderflow,
    InvalidRlp,
    InvalidJumpDestination,
    InvalidJumpiDestination,
    StackOverflow,
    KernelPanic,
    MemoryError(MemoryError),
    GasLimitError,
    InterpreterError,
    IntegerTooLarge,
    ProverInputError(ProverInputError),
    UnknownContractCode,
}

/// Enumerates memory related errors: these errors are
/// generated when either the context, the segment
/// or the virtual address is too large.
#[allow(clippy::enum_variant_names)]
#[derive(Debug)]
pub enum MemoryError {
    ContextTooLarge { context: U256 },
    SegmentTooLarge { segment: U256 },
    VirtTooLarge { virt: U256 },
}

/// Enumerates the errors which can be generated by `prover_input`.
#[derive(Debug)]
pub enum ProverInputError {
    OutOfMptData,
    OutOfRlpData,
    CodeHashNotFound,
    InvalidMptInput,
    InvalidInput,
    InvalidFunction,
}
